// P2-9 regression: tag noise must not outvote the problem signature.
//
// similarity() averaged two components with equal weight:
//
//     (jaccard(tags) + jaccard(problem_tokens)) / 2
//
// So two entries describing the IDENTICAL problem (problem-jaccard 1.0) whose
// tags merely diverged (tag-jaccard 0.5) scored (1.0 + 0.5) / 2 = 0.75, under
// the 0.85 gate — and a duplicate got written.
//
// The asymmetry that makes equal weighting wrong: tags are generated by
// substring-matching a fixed 13-word candidate list (agents/compound.ts), i.e.
// noisy by construction, while `problem` is the entry's actual content. Giving
// a heuristic label the same vote as the substance lets noise decide, and the
// polluted corpus is what researcher.history later mines — the dedup gate is
// the only thing standing between the knowledge engine and slow rot.

import { describe, expect, test } from "bun:test"
import { similarity, DEDUP_THRESHOLD } from "../../src/dispatcher/dedup"
import type { SimilarityCandidate } from "../../src/dispatcher/dedup"

const PROBLEM = "null pointer crash on login authentication when the session expires"

const cand = (tags: string[], problem = PROBLEM): SimilarityCandidate => ({
  signature: "",
  tags,
  problem,
})

describe("similarity weighting (P2-9)", () => {
  test("identical problem + half-matching tags is a duplicate (the audit case)", () => {
    // tag-jaccard = |{auth}| / |{auth,login,session}| = 1/3 here; the point is
    // that partial tag divergence must not veto an identical problem.
    const s = similarity(cand(["auth", "login"]), cand(["auth", "session"]))
    expect(s).toBeGreaterThanOrEqual(DEDUP_THRESHOLD)
  })

  test("identical problem + fully disjoint tags still reads as a duplicate", () => {
    const s = similarity(cand(["auth"]), cand(["runtime"]))
    // Problem carries the weight; disjoint noise-tags cannot drag an identical
    // problem below the gate.
    expect(s).toBeGreaterThanOrEqual(DEDUP_THRESHOLD)
  })

  test("matching tags CANNOT promote two unrelated problems to duplicates", () => {
    // The inverse error: weighting must not let a shared label merge entries
    // that describe different things. This is the more dangerous direction —
    // a false merge silently loses knowledge.
    const s = similarity(
      cand(["auth"], "null pointer crash on login when the session expires"),
      cand(["auth"], "webpack bundle size regression after upgrading the loader"),
    )
    expect(s).toBeLessThan(DEDUP_THRESHOLD)
  })

  test("identical signature still short-circuits to 1.0", () => {
    const a: SimilarityCandidate = { signature: "abc", tags: ["x"], problem: "p" }
    const b: SimilarityCandidate = { signature: "abc", tags: ["y"], problem: "q" }
    expect(similarity(a, b)).toBe(1)
  })

  test("ALG-1 holds: two information-free entries never merge", () => {
    expect(similarity(cand([], ""), cand([], ""))).toBe(0)
  })

  test("problem-only comparison is unaffected when neither side has tags", () => {
    // Tag component absent on both sides → problem alone decides, exactly as
    // before the weighting change.
    expect(similarity(cand([], PROBLEM), cand([], PROBLEM))).toBe(1)
  })

  test("untagged sentinel still compares on problem alone", () => {
    expect(similarity(cand(["untagged"], PROBLEM), cand([], PROBLEM))).toBe(1)
  })
})
